### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by sam-pandey** [vital987/vubuntu#1]
I'm getting this one when i tap on Deploy now 
#1 There was an issue setting up your app environment.

#Name is invalid
What should I use?

**Comment by apoorvvyavahare** [comment]
You need to manually deploy it by forking it and deploying it manually from heroku dashboard, I researched about this issue but didn't got anything, I asked on heroku help forum and waiting for  reply.

**Comment by sam-pandey** [comment]
Ok trying

**Comment by apoorvvyavahare** [comment]
Worked?

**Comment by vital987** [comment]
Heroku deployment error resolved, now project can be deployed to heroku using deploy button.
