### ISSUE TITLE
work flawlessly with new release.

### ISSUE THREAD

**Issue by ignisc4t** [vital987/vubuntu#11]
hi, thanks for updating the repo. just finishing my deploy and it works flawlessly in vnc, even on android vnc.

I hope, you can fix the root issues soon, love your work mate.

-you can close this, since this is the issues we all had at this moment.

**Comment by vital987** [comment]
The root access depends on the platform, Heroku dosen't allow root access, whereas Railway.app does but VNCs are prohibited on Railway so I am not suggesting it.
