### ISSUE TITLE
Sudo

### ISSUE THREAD

**Issue by HimuWorks** [vital987/vubuntu#16]
I am unable to use sudo command saying
Must be owned by uid 0 and have the setuid bit set 

And when I use pkexec bash command to fix it
Saying pkexec must be setuid root

Please tell me I am noob in this please help me out

Btw can I connect this to putty

**Comment by vital987** [comment]
Refer #7 , Talking about Putty, I didn't implemented SSH into the project cause SSH requires root and Heroku doesn't allow root access. You can access the terminal from the GUI/Desktop Env/Fluxbox.
