### ISSUE TITLE
IBM cloud foundry support? 

### ISSUE THREAD

**Issue by pipidaxian** [vital987/vubuntu#18]
Hi, thanks for your work. If possible, can this vnc app be deployed on IBM cloud foundry? 
I tried to “git clone” this app and pushed to IBM CF, but it failed.

**Comment by vital987** [comment]
> Hi, thanks for your work. If possible, can this vnc app be deployed on IBM cloud foundry? I tried to “git clone” this app and pushed to IBM CF, but it failed.

The app is normally built, like a docker image should be, there might be some custom config files of cloudfoundry like __heroku.yml__ & __app.json__ for Heroku, fork the project and modify accordingly. I don't exactly know what is cloud foundry but I've released docker images for latest and minimal version (purevnc minimal is in development so currently unavailable), so if cloud foundry has an option to directly deploy docker images with custom environment variables, you can do that else if you can get a VM instance, install docker and deploy the image manually or get a Ubuntu 20.04 LTS VM and install packages directly into it by following instructions from the Dockerfile. Close the issue if you are satisfied with the answer.

**Comment by vital987** [comment]
Try refering [these](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html) docs.
