### ISSUE TITLE
vubuntu was installed on my hacked heroku account 

### ISSUE THREAD

**Issue by kubilayeldemir** [vital987/vubuntu#19]
It was running on a container with maximum dynos possible(5k$ per month)
Just asking for fun.
Do you have any idea what vubuntu can be used for by hackers?
![hacked](https://user-images.githubusercontent.com/61070393/142265977-b282df3c-f1ac-4ce1-adf3-43102b743f00.png)

**Comment by vital987** [comment]
Vubuntu is a simple VNC+Fluxbox package for headless servers to ease the work, anyone can fork and modify the project so it depends on person how he uses it. In case of Heroku, one cannot use tools that requires root cause Heroku dosen't provide root access to their dynos.
