### ISSUE TITLE
heroku builapack needed for deploy process

### ISSUE THREAD

**Issue by claimclone** [vital987/vubuntu#2]
hi apoorv ,
im trying to deploy but deploy is failed because dockerfile buildlog neede or ... buildlog idk.
waiting for your response
finest regards

**Comment by vital987** [comment]
Can you send screenshot of the issue?

**Comment by claimclone** [comment]
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -P /tmp && 	apt install -y /tmp/packages-microsoft-prod.deb && 	apt update && 	apt-get install -y powershell' returned a non-zero code: 1

**Comment by claimclone** [comment]
full build log is long & can't be save .

**Comment by vital987** [comment]
It has been observed that you've made inappropriate changes in ```heroku.yml```.
Kindly re-fork (updated some work at my repo) the repo and **just change the environment variables, nothing else, then deploy it.**
