### ISSUE TITLE
Vubuntu XFCE

### ISSUE THREAD

**Issue by ochen1** [vital987/vubuntu#22]
This repository is tagged with the XFCE topic. Does Vubuntu have built-in support for XFCE?

**Comment by vital987** [comment]
By default it's not. But it can be added, check the commented section in Dockerfile. Heroku didn't had enough memory to support desktop environments so I switched to fluxbox. Also you need to make some additional changes including commenting the fluxbox installation commands.

**Comment by ochen1** [comment]
That's great. Thank you so much!
