### ISSUE TITLE
What is the password protected asset mods.7z?

### ISSUE THREAD

**Issue by beckerben** [vital987/vubuntu#27]
Was about to use this as it looks handy but not sure what this asset is, looks suspect...

**Comment by vital987** [comment]
They're modded deb packages for fluxbox and noVNC. I cannot make those files public as the [fluxbox code](https://github.com/fluxbox/fluxbox) doesn't have a GNU license, so the modified code cannot be shared publicly. I can share you the password via email.

**Comment by beckerben** [comment]
Got it and no need, thank you for the clarification!
