### ISSUE TITLE
Deployment Stalls at "Run scripts & scale dynos"

### ISSUE THREAD

**Issue by ntilikp** [vital987/vubuntu#3]
<img width="660" alt="Screen Shot 2021-07-13 at 11 57 14 PM" src="https://user-images.githubusercontent.com/56405695/125558782-28993ade-e956-4cd7-af80-83d59e42f1e5.png">

It's been stuck at this point for hours, is this normal?

**Comment by vital987** [comment]
I tested heroku deployment now on my personal account and it worked without any errors, repeat the whole process again. The docker image is huge and it's building time is somewhat close to heroku's app compiling limit, it should be the reason.
