### ISSUE TITLE
Using this to extract archived files in Google Drive

### ISSUE THREAD

**Issue by ntilikp** [vital987/vubuntu#4]
Not an issue per se, but I'd like to know if this project is suitable for the task of extracting .rar files that're hosted on Google Drive -- so downloading from GD, extracting on Heroku, reuploading the unarchived file back to GD.  

I've tried sorting it out myself but haven't been able to install rclone.  Any ideas? Is it not something that this is capable of? Sorry for the beginner questions.

**Comment by vital987** [comment]
Yup, PeaZip is installed in vubuntu. Follow the steps:
* Download the RAR file.
* Open file manager and locate the RAR file.
* Right-click > Choose PeaZip
* You can do any operations from GUI.
* Also you can open PeaZip from options.
* Options > Utilities > PeaZip

**Comment by vital987** [comment]
Rclone uses FUSE to make a temporary volume to mount google drive using block device, heroku dosen't allow any third-party devices.
