### ISSUE TITLE
Root Privilege

### ISSUE THREAD

**Issue by Dhananjay-JSR** [vital987/vubuntu#7]
As the title suggest is there was to get root access on server ?? everytime I type su and enter password which I entered when creating heroku app , it throws me with Authentication failure

**Comment by vital987** [comment]
The title is correct from every aspect & I wrote it as per over all image consideration, not only heroku and the password in the environment variable as it's name suggests, is the password of the VNC server, not of the password of the root user as the **project runs as root user without any password  but Heroku replaces it with it's custom user to prevent root access**.

**Comment by vital987** [comment]
Added support for railway.app, it supports root.

**Comment by armin-malek** [comment]
edit the docket file for installing custom software and giving permission that's the only way

**Comment by drhoangzp** [comment]
please tell me how to get root password in vubuntu, vital987?

**Comment by vital987** [comment]
https://github.com/vital987/vubuntu/issues/7#issuecomment-890371747

**Comment by drhoangzp** [comment]
So can vital987 show me how to get root password by video.

**Comment by vital987** [comment]
> So can vital987 show me how to get root password by video.

There's no such thing as root password in this project. It's just a docker container running directly as root. It depends on the Docker host whether to run the container as root or as a custom user with least privileges locking root account. For example, Heroku prevents the root access for it's containers by replacing root user with a custom one with least privileges. So when you type ```sudo su``` or ```su -```, you just get the password prompt with no correct password as the root account is locked. Try running the project on a VM with root access, you'll directly login as root (#).
