### ISSUE TITLE
railway flagged

### ISSUE THREAD

**Issue by MaiSan0001** [vital987/vubuntu#8]
![image](https://user-images.githubusercontent.com/60112822/128003831-e198a266-8034-4995-85fc-25152a9c9584.png)
![image](https://user-images.githubusercontent.com/60112822/128003834-d7653afb-34f1-4d0f-8a07-47748dedade7.png)
![image](https://user-images.githubusercontent.com/60112822/128003837-d9d79148-8c66-4464-8a8a-d796fe409b6c.png)

**Comment by vital987** [comment]
Apologies, as per Railway ToS, using VNC/Desktops are prohibited, that's the reason I removed it's support, see the repo again.
